import { Button } from "@/components/ui/button"
import { BiSolidHomeAlt2 } from "react-icons/bi"
import { FiInbox } from "react-icons/fi"
import { TbLineScan } from "react-icons/tb"

import { headers } from "next/headers";
import { urbanist } from "@/lib/utils";

import { Metadata } from "next";
import ScanButton from "./scan-button";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function HomeLayout({ children }: {
    children: React.ReactNode
}) {

    const route = headers().get('next-url')!;

    return (
        <main className={`${urbanist.className} pt-5 relative h-[100dvh]`}>
            {children}

            <footer className="w-full absolute bottom-0 grid grid-cols-3 bg-slate-300">
                <Button variant={"ghost"}>
                    <BiSolidHomeAlt2 className={route?.includes('home') ? 'text-slate-900': 'text-white'}/>
                </Button>
                <ScanButton/>
                <Button variant={"ghost"}>
                    <FiInbox className={route?.includes('inbox') ? 'text-slate-900': 'text-white'}/>
                </Button>
            </footer>
        </main>
    )

}

