import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import './globals.css'
import PWALoader from './pwa-loader'
import QueryParamProvider from './query-param-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <QueryParamProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
        <Toaster/>
        <PWALoader/>
      </html>
    </QueryParamProvider>
  )
}
